### PR TITLE
operator images support multi platforms

### PR DESCRIPTION
**Pull request by JaredTan95**
fix https://github.com/SumoLogic/tailing-sidecar/issues/400

### CODE REVIEW

**Comment by JaredTan95** [comment]
> https://github.com/SumoLogic/sumologic-kubernetes-setup/blob/main/Makefile

ok, I will update soon.

**Review by swiatekm-sumo — APPROVED** [review]
LGTM. Can you also rebase on `main`? That should fix the failing check.

**Comment by JaredTan95** [comment]
> LGTM. Can you also rebase on `main`? That should fix the failing check.

done

**Comment by JaredTan95** [comment]
@swiatekm-sumo I forgat update multi-build in `dev_builds` stages.  I will open another PR to fix it. :-P

**Pull request merged**
