### PR TITLE
feat: add scc configuration

### PR DESCRIPTION
**Pull request by sumo-drosiek**
Signed-off-by: Dominik Rosiek <drosiek@sumologic.com>

### CODE REVIEW

**Review by kkujawa-sumo — APPROVED** [review]
Could you add this change also to `main` and ` release-v0.5` branches?

**Comment by sumo-drosiek** [comment]
sure, just fix the helm test which failed for unknown reason

**Comment by sumo-drosiek** [comment]
it passed now

**Comment by sumo-drosiek** [comment]
#381 #380

**Pull request merged**
